### ISSUE TITLE
green for correct hash

### ISSUE THREAD

**Issue by OmlineEditor** [CodeDead/DeadHash-android#10]
I ask you to change the color of the button to green if the hash is correct. it visually facilitate the search. it is more conveniently
![green](https://user-images.githubusercontent.com/13348933/123238257-03219b00-d4e7-11eb-9fc7-09589ad98de7.jpg)

**Comment by CodeDead** [comment]
Great suggestion, thank you! It will be added in the next build.

**Comment by CodeDead** [comment]
Hi there @OmlineEditor ,

This has been implemented in commit https://github.com/CodeDead/DeadHash-android/commit/c6436dbd9282c19b0c66fa43dc1fea82d994bc06 .
You should see the update appear in the Play Store very soon.

Kind regards
