### ISSUE TITLE
Crash when checking big size file

### ISSUE THREAD

**Issue by shuvashish76** [CodeDead/DeadHash-android#29]
### To Reproduce

Open DeadHash > Click on File path option > pick any big size file (in my case its ~1GB) > Calculate

### Logs

```
FATAL EXCEPTION: main
Process: com.codedead.deadhash, PID: 9428
java.lang.OutOfMemoryError: Failed to allocate a 1055034968 byte allocation with 3325119 free bytes and 508MB until OOM, target footprint 6650239, growth limit 536870912
	at y0.c.b(Unknown Source:10)
	at y0.c.<init>(Unknown Source:10)
	at com.codedead.deadhash.gui.MainActivity.p0(Unknown Source:118)
	at com.codedead.deadhash.gui.MainActivity.d0(Unknown Source:0)
	at b1.i.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7467)
	at com.google.android.material.button.MaterialButton.performClick(Unknown Source:3)
	at android.view.View.performClickInternal(View.java:7444)
	at android.view.View.access$3700(View.java:840)
	at android.view.View$PerformClick.run(View.java:28831)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8090)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

### Device info

App version: 1.7.8 (9) [F-Droid] 
Android release version: 12
Android SDK version: 31
Device brand: motorola
Device model: moto g71 5G

**Comment by CodeDead** [comment]
Sorry, can't be fixed. Your device does not have enough RAM to process the file in question.

**Comment by shuvashish76** [comment]
Ok but it should show the user that "Not enough RAM to process the file" or similar message, instead of just crashing.

**Comment by CodeDead** [comment]
> Ok but it should show the user that "Not enough RAM to process the file" or similar message, instead of just crashing.

Not possible. If a system runs out of RAM and is killed by Early loom or similar processes, there is no way to show the user that RAM is not sufficient. This is an exception that cannot be caught. The only way to get rid of it is to close apps, or install more RAM (which is generally impossible on phones).

**Comment by shuvashish76** [comment]
>  What you can try is to close running apps to free up some memory, and see if that solves the problem.
The only way to get rid of it is to close apps, or install more RAM (which is generally impossible on phones).

My device has 6GB RAM which is common these days. I think that's the limitations of this category (hash checking) android apps. 🤷🏿‍♂️

**Comment by CodeDead** [comment]
> >  What you can try is to close running apps to free up some memory, and see if that solves the problem.
> The only way to get rid of it is to close apps, or install more RAM (which is generally impossible on phones).
> 
> My device has 6GB RAM which is common these days. I think that's the limitations of this category (hash checking) android apps. 🤷🏿‍♂️

Probably. Depends on the file size that you're trying to calculate a hash for. If it exceeds your capacity, it's better to use a dedicated machine to calculate a hash. E.g. trying to calculate the hash of a 16gb file while only having 6gigs of RAM can't be done unless the file hash is calculated by streaming it piece by piece, something that not all algorithms even support. Even then you can run into limitations. It's unfortunate but we do have a desktop app available that will probably work better. Alternatively you can calculate hashes on a server but then the question of whether or not you can trust that server/connection to that server comes into play.

**Comment by CodeDead** [comment]
What I can do though is optimize the way hashes are calculated by streaming and updating the digest. It should improve things, but it is not guaranteed to work for every use-case.

Will be done in the next update.

**Comment by shuvashish76** [comment]
Agreed, I use [gtkhash](https://github.com/gtkhash/gtkhash) on my desktop :)

Isn't it possible to check system details (in this case RAM) when user installs the app & set predefined value for that. e.g - If the user has 3GB RAM & least try 500BM (or above) file then we show a message. (without processing the file hence without crash)

Values we set by testing various devices & file size...

**Comment by CodeDead** [comment]
> Agreed, I use [gtkhash](https://github.com/gtkhash/gtkhash) on my desktop :)
> 
> Isn't it possible to check system details (in this case RAM) when user installs the app & set predefined value for that. e.g - If the user has 3GB RAM & least try 500BM (or above) file then we show a message. (without processing the file hence without crash)
> 
> Values we set by testing various devices & file size...

That is possible, yes. Preventative measures where we can ask the user if they want to continue calculating the hash even though they might not have enough RAM. Thanks for brainstorming with me.

**Comment by shuvashish76** [comment]
Or even better check available free RAM each time the user pick a file for process.

**Comment by CodeDead** [comment]
> Or even better check available free RAM each time the user pick a file for process.

Available ram vs ram required to calculate the hash (estimate). Should do the trick.

**Comment by shuvashish76** [comment]
> My device has 6GB RAM which is common these days. I think that's the limitations of this category (hash checking) android apps. 🤷🏿‍♂️

Checked 1GB file with [this app](https://github.com/hash-checker/hash-checker), calculated instantly & it matched to my desktop gtkhash SHA256 result. Request to checks how this app works.

**Comment by CodeDead** [comment]
> > E.g. trying to calculate the hash of a 16gb file while only having 6gigs of RAM can't be done unless the file hash is calculated by streaming it piece by piece, something that not all algorithms even support.
> 
> Just to on safe side, like you said zipped multiple files ~16GB 😅 & checked with that app on my phone (6GB RAM). It took some time but again the result match to desktop result :D

They stream the file, something this app needs to do as well. Instead of reading the entire file to memory, they read bits of it and update it piece by piece. So those are two improvements that need to be implemented in DeadHash for Android.

**Comment by CodeDead** [comment]
This will be fixed along with some additional improvements in https://github.com/CodeDead/DeadHash-android/pull/33
