### ISSUE TITLE
[SUGGESTION] Dark theme

### ISSUE THREAD

**Issue by trymeouteh** [CodeDead/DeadHash-android#3]
Please add a light theme, dark theme, and a system theme setting

**Comment by CodeDead** [comment]
Thank you for the suggestion @trymeouteh . This will be added in the next release of DeadHash. The new version should be available by the end of this week.

**Comment by CodeDead** [comment]
Hello,

Your requested feature was added and will be available in the play store as soon as possible.
https://github.com/CodeDead/DeadHash-android/commit/ccc3336aee7618e962b91ea89f84477f17fd8b07

If you want to manually download and install the APK, you can find the latest release here:
https://github.com/CodeDead/DeadHash-android/releases/tag/1.7.4

Kind regards,

Alessandro Mercier
