### ISSUE TITLE
Storage permissions are required in order to use DeadHash

### ISSUE THREAD

**Issue by CaKrome** [CodeDead/DeadHash-android#37]
After upgrading to 1.8.1 from 1.7.8, the app won't select file anymore when pressing the folder button next to the file path textbox.

Looks like commit f75274ed3fcdb2612d092f84aa9b3b3b793b9908 might be the cause, it removed ```<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />``` from the `AndroidManifest.xml`

**Comment by CodeDead** [comment]
Hi @CaKrome thanks for reporting. What version of Android are you using, if I may ask?

**Comment by CaKrome** [comment]
I'm using Android 11

**Comment by CodeDead** [comment]
Thanks! I'll try and solve this elegantly, asap.

**Comment by CodeDead** [comment]
Fixed in https://github.com/CodeDead/DeadHash-android/tree/feature/permissions_fix

A release will be scheduled immediately and you will be able to download a signed apk from Github. The play store and fdroid releases will take a bit longer.
