### ISSUE TITLE
[SUGGESTION] F-Droid inclusion?

### ISSUE THREAD

**Issue by ClockGen** [CodeDead/DeadHash-android#4]
I'd like to include your app to F-Droid, which is a catalogue of FOSS apps and client and server software for its distribution. You can read more about F-Droid at http://f-droid.org/. As per inclusion policy, I must ask for your permission to do so.

**Comment by ClockGen** [comment]
Nevermind, found your own RFP at F-Droid. Gonna open a metadata MR soon.

**Comment by CodeDead** [comment]
@ClockGen Thank you for your willingness to help, if you do open a MR, would you like to be mentioned in the about information of the app itself as a token of appreciation?

**Comment by ClockGen** [comment]
> would you like to be mentioned
No need.
MR Progress:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8405
